[package]
name = "hyprclip"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
wl-clipboard-rs = "0.6"       # Clipboard-Zugriff unter Wayland
zbus = "3.14"                 # D-Bus Kommunikation
tray-icon = "0.7"             # Für Tray-Icon (XDG/StatusNotifier)
serde = { version = "1", features = ["derive"] }
serde_json = "1"